### ISSUE TITLE
git 협업 방법 변경

### ISSUE THREAD

**Issue by codeing999** [codeing999/CLIPs-backend#25]
기존 브랜치
main : 최종적으로 배포할 브랜치
submain : 각자의 작업 브랜치에서 작업하다가 에러 없이 작업 완료될 때마다 수시로 푸쉬할 브랜치
dev/닉네임 : 각자의 작업 브랜치. 

변경된 브랜치
main : 배포할 브랜치
develop : 개발 단계에서 각각의 기능이 완성될 때 마다 합칠 브랜치
feature/기능명, fix/에러 : 각 기능 단위로 브랜치를 새로 만들고 완성 시마다 develop에 합치고 이 브랜치는 삭제.

이 내용은 동의 하시면 docs에도 반영하여 수정하도록 하겠습니다.

**Comment by Rumaro122** [comment]
넵~ 새로운 방법인데 익숙해져야겠네요

**Comment by Minsun91** [comment]
네 좋습니다.
