### ISSUE TITLE
Joi를 이용한 유효성 검사에서 배열 안에 객체를 어떻게 검증할 것인가?

### ISSUE THREAD

**Issue by Rumaro122** [codeing999/CLIPs-backend#27]
- 문제점
- 
![image](https://user-images.githubusercontent.com/107511994/187714517-f5d90e21-6c77-474a-9c82-acbedae56a2b.png)

기존에는 Joi를 이용하여 주어진 특정 값. 예를 들어 string, number으로만 유효성 검사를 진행했었다. 지금 프로젝트에서는 약속을 생성할 시 배열 안에 고정되지 않은 객체들을 검증해야 하는데, 이를 joi를 통해서 어떻게 처리해야 할 것인가?

- 해결 방안

joi 문서를 살펴 보고, 구글링을 통해 비슷한 사례가 있는지 검색.

**Comment by codeing999** [comment]
https://joi.dev/api/?v=17.6.0#anywhencondition-options

공식문서에서 비슷한 것을 본 것 같습니다.

```javascript
const schema = Joi.object({
    a: Joi.boolean().required(),
    b: Joi.object()
        .keys({
            c: Joi.string(),
            d: Joi.number().required()
        })
        .required()
        .when('a', {
            is: true,
            then: Joi.object({ c: Joi.required() })		// b.c is required only when a is true
        })
});
```
특히 이 부분을 살펴보시면 도움이 될 것 같습니다

**Comment by Rumaro122** [comment]
.keys({옵션})을 통해 객체 안에 있는 정보들에 대한 유효성 검사를 실시할 수 있군요 👍
