### ISSUE TITLE
다대다 관계로 연결된 user와 promise를 friend라는 테이블로 연결 시켜 자동 생성되게 하였는데 어떻게 데이터를 삽입해야하는가?

### ISSUE THREAD

**Issue by Rumaro122** [codeing999/CLIPs-backend#46]
# 문제점

![image](https://user-images.githubusercontent.com/107511994/188396447-847cabe9-c1d2-4e17-8b05-8b67c1790d66.png)
![image](https://user-images.githubusercontent.com/107511994/188396574-b34a2081-3435-4b69-a33d-fdd718bec0be.png)

## 작업 내용 

![image](https://user-images.githubusercontent.com/107511994/188396718-6c5f2b99-b400-4d32-87f3-99066c83dfbe.png)

기존에는 모델에서 export한 내용을 require를 통해서 불러와서 테이블명.create/update/findAll 등 필요에 따라 뒤에 sequelize 내장 함수를 사용하여 CRUD 작업을 수행할 수 있었다. 그러나, Friend라는 모델은 별도로 설정하여 생성한 적이 없고, User와 Promise 테이블의 관계 설정을 할 시 through를 통해 자동 생성 된 것이기에 모델로 불러올 값이 존재하지 않아 어떻게 해야 데이터를 삽입할 수 있는지 애매하다. 

## 의도한 결과 

기존 방식을 await Friend.create를 했었는데, 생각해보니 Friend라는 모델은 존재하지 않았다. 모델로 생성하지 않은 테이블에 대한 접근을 할 수 있는 방식을 찾아내야 한다.

## 실제 결과 

Friend에는 객체로 받은 값을 분해하여 for문을 통해 하나씩 삽입하려고 했으나, friend 테이블에 데이터를 삽입하지 못하여 for 루프가 종료되어 에러를 내뱉었다. Friend에 대한 접근을 할 수 없다는 것을 알 수 있게 되었다.

# 조치 사항

열심히 구글링 구글링... 지금까지 본 해결책으로는 모델을 정의해줘서 접근할 수 있는 경로를 만들어주는 것이 가장 일반적이고 쉬운 방법이라고 생각하는데, Workbench를 통해 살펴본 DB에서는 분명 friend라는 테이블이 존재한다. 단지 어떻게 접근할 수 있는지를 아직 알아내지 못했을뿐... 생성된 만큼 모델을 따로 설정하지 않아도 접근을 할 수 있지 않을까? 라는 생각을 가지고 있고 모델을 재설정 하지 않고 접근할 수 있는 방법을 알아내고자 한다.

**Comment by codeing999** [comment]
const db = require("../../sequelize/models");
const Friend = db.sequelize.models.Friend;
를 레포지토리에 추가해보면 될 것 같습니다.
