### ISSUE TITLE
AWS Code Pipeline

### ISSUE THREAD

**Issue by codeing999** [codeing999/CLIPs-backend#66]
배포를 성공했는데 이제 그걸 자동화하는 것이 파이프라인이라고 한다.
(이 단계를 깃헙 액션으로 하는 방법도 있는 것 같기도 한데 그걸 하려면 s3를 사용해야하는 것 같다. )

파이프라인 -> 파이프라인 생성을 누르고

파이프라인 이름 입력,
나머진 그대로 놔두고 다음

소스공급자는 github(버전2)

그 뒤 연결에서 github에 연결

![image](https://user-images.githubusercontent.com/109027875/189679554-6f299ad5-cd7d-434c-9bcc-9b33188d8291.png)

뭐 이런 화면 등등 지나간다.

저 인스톨 누르면

![image](https://user-images.githubusercontent.com/109027875/189681320-75ad8aa0-1502-4860-9dd1-b20f55963d36.png)

이렇게 연결에 어떤 숫자가 부여되어진다.

![image](https://user-images.githubusercontent.com/109027875/189682513-dad81008-a718-4338-ae4a-87582e40fe22.png)

![image](https://user-images.githubusercontent.com/109027875/189683140-360c48ba-3b54-4235-8548-fa1d1fa98ee0.png)

빌드스테이지는 건너뛰고

![image](https://user-images.githubusercontent.com/109027875/189683493-962aea39-8b90-46bb-a816-138e4a481243.png)

공급자에 AWS CodeDeploy 입력하면
밑에꺼는 우리가 만들었던 것들 자동으로 뜬다. 그것을 선택하면 된다.

내가 [참고한 사이트](https://iot624.tistory.com/180#%F0%9F%93%8C_CodePipeline_%EC%9D%84_%ED%86%B5%ED%95%9C_%EB%B0%B0%ED%8F%AC_%EC%9E%90%EB%8F%99%ED%99%94)

는 여기서 권한 부족이 떴다는데 다행히 난 이미 권한을 잘 해준 모양이다.

![image](https://user-images.githubusercontent.com/109027875/189684371-bc7e460c-7721-4637-881e-5d6d295fddee.png)

이와 같이 파이프라인 생성 성공!

그 뒤는 git bash에서 PM2가 없다면 설치해주고

pm2가 서버를 실행하도록 ecosystem.json 파일을 루트경로에 다음과 같은 형식으로 만들어준다.
```
{
    "apps": [
        {
            "name": "project-name",
            "script": "./node_modules/.bin/ts-node",
            "args": "./src/index.ts",
            "watch": true
        }
    ]
}
```

일단 더할게 있는 것 같은데

**Comment by kpzzy** [comment]
유용한,,,정보,,,감사,,,합니다,,,,, ^^
